### PR TITLE
Compile OpenMPI with CUDA

### PR DESCRIPTION
**Pull request by OmriShiv**
Compile OpenMPI with CUDA

### CODE REVIEW

**Comment by alsrgv** [comment]
@OmriShiv, thanks for the pull request.  What's the desire to use CUDA-aware Open MPI?  [NCCL developer guide](http://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/index.html#intergpu) mentions the possibility of deadlock with NCCL + CUDA-aware MPI combination that few Horovod customers reported as well, so it may not be a great idea to enable it in the general purpose container.

**Comment by OmriShiv** [comment]
@alsrgv We had not run into that issue, thankfully, but also had not seen that in the developer guide; thanks for the reference! We'll keep an eye out to see if affects us.

**Comment by alsrgv** [comment]
@OmriShiv, sounds good.  I think we should keep it as a private change for now, until NCCL fixes deadlocks if that's possible.

**Comment by OmriShiv** [comment]
@alsrgv Agreed; feel free to close.

**Pull request closed without merging**
