### PR TITLE
Export only Horovod symbols

### LINKED ISSUE #462: Hide third-party symbols to avoid conflicts
I was investigating a segfault with the following trace:
```
[ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f57f51ff390]
[ 1] /HOME/.local/lib/python3.6/site-packages/horovod/common/mpi_lib.cpython-36m-x86_64-linux-gnu.so(_ZN11flatbuffers15vector_downward10reallocateEm+0x2f)[0x7f56fae87d0f]
[ 2] /HOME/.local/lib/python3.6/site-packages/pyarrow/libarrow.so.10(+0x1c9edb)[0x7f56f9716edb]
[ 3] /HOME/.local/lib/python3.6/site-packages/pyarrow/libarrow.so.10(_ZN5arrow3ipc8internal23WriteRecordBatchMessageEllRKSt6vectorINS1_13FieldMetadataESaIS3_EERKS2_INS1_14BufferMetadataESaIS8_EEPSt10shared_ptrINS_6BufferEE+0xd2)[0x7f56f97174a2]
[ 4] /HOME/.local/lib/python3.6/site-packages/pyarrow/libarrow.so.10(_ZN5arrow3ipc16WriteRecordBatchERKNS_11RecordBatchElPNS_2io12OutputStreamEPiPlPNS_10MemoryPoolEib+0x29b)[0x7f56f9729f8b]
[ 5] /HOME/.local/lib/python3.6/site-packages/pyarrow/libarrow.so.10(_ZN5arrow3ipc23RecordBatchStreamWriter16WriteRecordBatchERKNS_11RecordBatchEb+0xfb)[0x7f56f972a5eb]
[ 6] /HOME/.local/lib/python3.6/site-packages/pyarrow/libarrow.so.10(_ZN5arrow3ipc22WriteRecordBatchStreamERKSt6vectorISt10shared_ptrINS_11RecordBatchEESaIS4_EEPNS_2io12OutputStreamE+0x12a)[0x7f56f97284ba]
[ 7] /HOME/.local/lib/python3.6/site-packages/pyarrow/libarrow_python.so.10(_ZN5arrow2py18SerializedPyObject7WriteToEPNS_2io12OutputStreamE+0x126)[0x7f56f9315dc6]
[ 8] /HOME/.local/lib/python3.6/site-packages/pyarrow/lib.cpython-36m-x86_64-linux-gnu.so(+0xd6389)[0x7f56f9d22389]
[ 9] python(+0x10eb28)[0x55f96cae4b28]
...
```

It can be seen from the above stack trace, that pyarrow is using flatbuffers, and it calls into horovod for the function `_ZN11flatbuffers15vector_downward10reallocateEm`.

Since horovod is vendoring it's own version of flatbuffer, it has the potential to cause problems if mixed with a different version of flatbuffer. Although I'm not sure if this is the cause to my problems, but horovod should mark non-horovod symbols as `bind=LOCAL`, rather than `WEAK`, or `visibility=HIDDEN`, rather than `DEFAULT`:
```
$ readelf -Ws common/mpi_lib.cpython-36m-x86_64-linux-gnu.so |grep flatbuffer
    32: 000000000492ff90    48 OBJECT  WEAK   DEFAULT   24 _ZTVN11flatbuffers16simple_allocatorE  
   109: 0000000000020640    54 FUNC    WEAK   DEFAULT   11 _ZNSt8_Rb_treeIN11flatbuffers6OffsetINS0_6StringEEES3_St9_IdentityIS3_ENS0_17FlatBufferBuilder19StringOffsetCompareESaIS3_EE8_M_eraseEPSt13_Rb_tree_nodeIS3_E
   110: 000000000001ecd0     8 FUNC    WEAK   DEFAULT   11 _ZNK11flatbuffers16simple_allocator8allocateEm                                                                                           
   179: 00000000000164f0 10251 FUNC    GLOBAL DEFAULT   11 _ZN7horovod6common27MPIResponse_SerializeToWireERKNS0_11MPIResponseERN11flatbuffers17FlatBufferBuilderERNS4_6OffsetINS0_4wire11MPIResponseEEE
   195: 000000000001ec90     2 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers16simple_allocatorD1Ev 
   236: 0000000000020710   230 FUNC    WEAK   DEFAULT   11 _ZNSt6vectorIN11flatbuffers17FlatBufferBuilder8FieldLocESaIS2_EE19_M_emplace_back_auxIIRKS2_EEEvDpOT_                                    
   239: 000000000001ece0   185 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers15vector_downward10reallocateEm                                                                                          
   245: 0000000000020680   142 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers17FlatBufferBuilderD2Ev                                                                                                     254: 000000000001eca0     5 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers16simple_allocatorD0Ev 
   275: 00000000000789e0    34 OBJECT  WEAK   DEFAULT   13 _ZTSN11flatbuffers16simple_allocatorE  
   300: 0000000000020680   142 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers17FlatBufferBuilderD1Ev                                                                                                     306: 00000000000208d0  2308 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers17FlatBufferBuilder8EndTableEjt                                                                                          
   380: 000000000001ecb0    18 FUNC    WEAK   DEFAULT   11 _ZNK11flatbuffers16simple_allocator10deallocateEPh                                                                                       
   406: 000000000492ff80    16 OBJECT  WEAK   DEFAULT   24 _ZTIN11flatbuffers16simple_allocatorE  
   408: 0000000000020710   230 FUNC    WEAK   DEFAULT   11 _ZNSt6vectorIN11flatbuffers17FlatBufferBuilder8FieldLocESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_                                    
   429: 000000000001ec90     2 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers16simple_allocatorD2Ev 
   468: 0000000004931b70     8 OBJECT  WEAK   DEFAULT   28 _ZN11flatbuffers25flatbuffer_version_stringE                                                                                             
    91: 000000000001a9d0  6375 FUNC    LOCAL  DEFAULT   11 _ZN7horovod6common12_GLOBAL__N_126MPIRequest_SerializeToWireERKNS0_10MPIRequestERN11flatbuffers17FlatBufferBuilderERNS5_6OffsetINS0_4wire10MPIRequestEEE.constprop.287
  1854: 000000000492ff90    48 OBJECT  WEAK   DEFAULT   24 _ZTVN11flatbuffers16simple_allocatorE  
  1931: 0000000000020640    54 FUNC    WEAK   DEFAULT   11 _ZNSt8_Rb_treeIN11flatbuffers6OffsetINS0_6StringEEES3_St9_IdentityIS3_ENS0_17FlatBufferBuilder19StringOffsetCompareESaIS3_EE8_M_eraseEPSt13_Rb_tree_nodeIS3_E
  1932: 000000000001ecd0     8 FUNC    WEAK   DEFAULT   11 _ZNK11flatbuffers16simple_allocator8allocateEm                                                                                           
  2001: 00000000000164f0 10251 FUNC    GLOBAL DEFAULT   11 _ZN7horovod6common27MPIResponse_SerializeToWireERKNS0_11MPIResponseERN11flatbuffers17FlatBufferBuilderERNS4_6OffsetINS0_4wire11MPIResponseEEE
  2017: 000000000001ec90     2 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers16simple_allocatorD1Ev 
  2058: 0000000000020710   230 FUNC    WEAK   DEFAULT   11 _ZNSt6vectorIN11flatbuffers17FlatBufferBuilder8FieldLocESaIS2_EE19_M_emplace_back_auxIIRKS2_EEEvDpOT_                                    
  2061: 000000000001ece0   185 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers15vector_downward10reallocateEm                                                                                          
  2067: 0000000000020680   142 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers17FlatBufferBuilderD2Ev                                                                                                  
  2076: 000000000001eca0     5 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers16simple_allocatorD0Ev 
  2097: 00000000000789e0    34 OBJECT  WEAK   DEFAULT   13 _ZTSN11flatbuffers16simple_allocatorE  
  2122: 0000000000020680   142 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers17FlatBufferBuilderD1Ev                                                                                                  
  2128: 00000000000208d0  2308 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers17FlatBufferBuilder8EndTableEjt                                                                                          
  2202: 000000000001ecb0    18 FUNC    WEAK   DEFAULT   11 _ZNK11flatbuffers16simple_allocator10deallocateEPh                                                                                       
  2228: 000000000492ff80    16 OBJECT  WEAK   DEFAULT   24 _ZTIN11flatbuffers16simple_allocatorE  
  2230: 0000000000020710   230 FUNC    WEAK   DEFAULT   11 _ZNSt6vectorIN11flatbuffers17FlatBufferBuilder8FieldLocESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_                                    
  2251: 000000000001ec90     2 FUNC    WEAK   DEFAULT   11 _ZN11flatbuffers16simple_allocatorD2Ev 
  2290: 0000000004931b70     8 OBJECT  WEAK   DEFAULT   28 _ZN11flatbuffers25flatbuffer_version_stringE  
```

### PR DESCRIPTION
**Pull request by alsrgv**
Fixes #462

### CODE REVIEW

**Comment by tals** [comment]
I'm being bitten by this. Any idea when it will make it to a release? :)

**Comment by alsrgv** [comment]
@tals, it is available since Horovod 0.14.0.  Which version are you using?

**Comment by tals** [comment]
@alsrgv ahh my bad, didn't realize 0.14.0 was out :)
Thanks!

**Comment by alsrgv** [comment]
@tals, 0.15.0 is out, and 0.15.1 is one foot out of the door :-)

**Pull request merged**
